<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_History_w-6 h-6 mb-1 filter-blue</name>
   <tag></tag>
   <elementGuidId>d3371031-c06f-46ac-bdcc-7c240a80032d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/footer/a[4]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.w-6.h-6.mb-1.filter-blue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Profile Profile&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>95b9ace7-dae4-4108-824a-3ff17af9f53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/user-octagon.png</value>
      <webElementGuid>16cb5b72-9d5a-49c8-a4a6-52f9f8a8c1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Profile</value>
      <webElementGuid>5882f408-f7bc-4a6d-80ba-a7098493f791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-6 h-6 mb-1 filter-blue</value>
      <webElementGuid>0db51125-2a38-433f-9787-ba6cbceda1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;max-w-sm w-full mx-auto bg-gray-100 min-h-screen&quot;]/footer[@class=&quot;fixed bottom-0 left-0 right-0 bg-white shadow-md flex justify-around py-2 max-w-sm w-full mx-auto&quot;]/a[@class=&quot;flex flex-col items-center text-blue-800&quot;]/img[@class=&quot;w-6 h-6 mb-1 filter-blue&quot;]</value>
      <webElementGuid>7445a5f7-c989-41b8-9917-596c5ed0e2ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/footer/a[4]/img</value>
      <webElementGuid>eccb162d-e274-4e16-a163-25bd184d5d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Profile']</value>
      <webElementGuid>eab22c0e-e031-451a-a8ef-045f403b37f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/img</value>
      <webElementGuid>e789c583-35ab-4e94-825a-5cfb93eb6185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/icons/user-octagon.png' and @alt = 'Profile']</value>
      <webElementGuid>d6286e17-d23f-467e-854e-b4b0d1dc848d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
