<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Error Failed to update profile</name>
   <tag></tag>
   <elementGuidId>bcaa9b9f-77a0-431c-9b65-2864b8278281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-red-500</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Error: Failed to update profile&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7a2559b-5aa7-4998-8081-fa1251cbd04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-red-500</value>
      <webElementGuid>37ea4e54-6669-4b63-9fca-dd5c5f292cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error: Failed to update profile</value>
      <webElementGuid>e64217ec-7d3e-4a49-819d-28da876be4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;max-w-sm w-full mx-auto bg-gray-100 min-h-screen&quot;]/div[@class=&quot;text-red-500&quot;]</value>
      <webElementGuid>0095b32b-668e-4313-bf67-df73d86db73f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div</value>
      <webElementGuid>dbb2bec4-dc88-49e4-87a9-84f93df7121a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::div[1]</value>
      <webElementGuid>a0d418d4-d318-4b47-9bde-34ac72888761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request'])[1]/preceding::div[1]</value>
      <webElementGuid>1756cd89-5d3f-407a-819e-5f65ca27811b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Error:']/parent::*</value>
      <webElementGuid>0203e9de-d966-48f8-b7e4-8bee071ca918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>d8973289-58a8-451b-bf0e-2d08dabc16df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Error: Failed to update profile' or . = 'Error: Failed to update profile')]</value>
      <webElementGuid>5dda9bf3-4fc6-4e68-8afa-395157d1c0a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
