<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OTP_border rounded-md px-3 py-2 w-full</name>
   <tag></tag>
   <elementGuidId>1905894e-c056-4da6-8e4b-33b38e1a5bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='123456']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[type=&quot;text&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b864097-40a1-4490-b86b-63d0b15b1035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>231bf5a5-b610-4cce-a4e0-411674700b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border rounded-md px-3 py-2 w-full</value>
      <webElementGuid>7c859df6-b68f-4c4c-a8d6-9a2560e213bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>123456</value>
      <webElementGuid>75fe29c0-fb9e-45b3-a4cc-d1fbe98bce53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;max-w-sm w-full mx-auto bg-gray-100 min-h-screen&quot;]/div[@class=&quot;p-4&quot;]/div[@class=&quot;bg-white p-6 rounded-lg shadow-md&quot;]/div[@class=&quot;mb-4&quot;]/input[@class=&quot;border rounded-md px-3 py-2 w-full&quot;]</value>
      <webElementGuid>a9cf8af5-23f1-4a7c-ac2e-b946aa8a1931</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='123456']</value>
      <webElementGuid>fd67ea08-d696-40f5-8b76-9ceb0822d489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/input</value>
      <webElementGuid>f6a6cc95-b908-4d73-b444-651403d054aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>15ec8e95-d090-4572-97e1-50f0d1c29c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>098880f4-0da5-4ef0-826c-fe14262acaac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
